name: Django CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:16.2-alpine
        ports:
          - "5433:5433"
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install docker-ce docker-compose
        sudo usermod -aG docker $USER

    - name: Start Docker
      run: sudo service docker start

    - name: Build and run web service
      run: docker-compose up --build --detach

    - name: Run tests
      run: docker-compose exec web python manage.py test

    - name: Stop and remove web service
      run: docker-compose down

    - name: Build Docker image
      run: docker-compose build


