name: Django CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

#    services:
 #     db:
  #      image: postgres:16.2-alpine
   #     ports:
    #      - "5432:5432"
     #   env:
      #    POSTGRES_DB: postgres
       #   POSTGRES_USER: postgres
        #  POSTGRES_PASSWORD: postgres

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install docker-ce docker-compose
        sudo usermod -aG docker $USER

    - name: Start Docker
      run: sudo service docker start

    - name: Build and run web service
      run: docker-compose up -d

    - name: Wait for DB container to be ready
      run: |
          for i in {1..10}; do
            nc -zv localhost 5432 && echo "DB container is ready" && exit 0
            echo "Waiting for DB container..."
            sleep 5
          done
          echo "DB container failed to start"
          exit 1
          
    - name: Run tests
      run: docker exec web python manage.py test

    - name: Stop and remove web service
      run: docker-compose down

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)


